### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DarioAlessioR**
Update contributions section of README

### CODE REVIEW

**Review by Mre55 — CHANGES_REQUESTED** [review]
**Hi @DarioAlessioR,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 

- [ ] As the project [requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md#requirements) you should have to add a `.gitignore` file not `.gitignore.txt` file. Kindly update the file it should not have any extension.

- [ ] Please update the Pull Request title to have a descriptive title telling you what changes are inside and also update the Pull Request description to have a summary describing introduced changes in more detail. 

- [x] Also for future reference don't close any branch without getting approval to continue working on that branch. I notice you closed one branch and submit a new pull request created from that branch.




## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DarioAlessioR** [comment]
PR due to 3 changes:
1) Update the Contribution section in the README file
2) Delete file .gitignore.txt, which is wrong, as project instructions state it must be .gitignore without extension
3) Add file .gitignore

These changes were suggested by @Mre55 as part of a Code Review. Thanks a lot for your needed review and suggestions @Mre55 .

**Comment by DarioAlessioR** [comment]
Thank you very much for your kind ***@***.***
I already fixed the project.
(Sorry, I'm new to all of it, this is my second day at Microvers, so please excuse me if this is not the proper way to communicate with you).
Thank you in advance.
Dario.
    On Tuesday, April 19, 2022, 07:48:18 PM GMT-4, Mihreteab Misganaw ***@***.***> wrote:  
 
 


@Mre55 requested changes on this pull request.

Hi @DarioAlessioR,

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

To highlight 🎯
    
   - The Pull Request is following the GitHub Flow ✅
   - The commit messages are meaningful ✅
   - The README is well documented ✅
   - Linters are working properly ✅

Required Changes ♻️ 🛠️
    
   -    
 As the project requirement you should have to add a .gitignore file not .gitignore.txt file. Kindly update the file it should not have any extension.

   -    
 Please update the Pull Request title to have a descriptive title telling you what changes are inside and also update the Pull Request description to have a summary describing introduced changes in more detail.

   -    
 Also for future reference don't close any branch without getting approval to continue working on that branch. I notice you closed one branch and submit a new pull request created from that branch.




Optional suggestions 🟡
 
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏 👏 👏
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

**Review by keroloussamy — APPROVED** [review]
Hi @DarioAlessioR, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

clap

## Optional suggestions
_Check the comments under the review._

- [ ] You can update your PR, by click the 3 dots and click Edit option. Instead of make a new comment for the PR.
image
  

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DarioAlessioR** [comment]
Merge SecondBranch into master branch after approval by second reviewer @keroloussamy . Thank you a lot for your professional support @keroloussamy and @Mre55 .

**Pull request merged**
